version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  home:
    lang: node
    handler: ./source/home
    image: ad-si/home:latest

  birthday-reminder:
    lang: node
    handler: ./source/birthday-reminder
    image: ad-si/birthday-reminder:latest
